### ISSUE TITLE
ESM - ECMAScript Modules with JavaScript mock data

### ISSUE THREAD

**Issue by danactive** [architect/plugin-lambda-invoker#6]
**Describe the issue**
Node.js cannot be configured to ECMAScript modules (ESM) with a JavaScript mock data file.

JavaScript mock data must use CommonJS (CJS) export syntax `module.exports` with Node.js configured to support CJS (in package.json `type` must be omitted or set to "commonjs")

If Node.js is configured to ESM then the JavaScript mock data hits an exception on this [line 75](https://github.com/architect/plugin-lambda-invoker/blob/v1.0.1/src/index.js#L75)

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Update **packge.json** to `"type": "module",`
2. Touch a file in the root with filename `sandbox-invoke-mocks.js`
3. Define a mock structure with `module.exports` as _.CJS_ or `export default` syntax _.JS_ or _.MJS_

**Expected behaviour**
Execute lambda function with mock data

**Actual behaviour**

An empty mock event is passed to the Lambda function if the JavaScript mock file is a _.CJS_

ESM error if the JavaScript mock file is a _.JS_ or _.MJS_
```
/Users/.../node_modules/@architect/plugin-lambda-invoker/src/index.js:75
            mocks = require(jsMocks)
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/.../sandbox-invoke-mocks.js from /Users/.../node_modules/@architect/plugin-lambda-invoker/src/index.js not supported.

```

**Screenshots**
If applicable, add screenshots to help explain your problem

<img width="1194" alt="Screenshot 2023-08-07 at 13 07 31" src="https://github.com/architect/plugin-lambda-invoker/assets/1093286/265cce10-2ba9-4b87-89a9-b685ad900e89">

**Environment**
Please complete the following information (if appropriate):
 - OS: macOS Ventura 13.4 (with Apple Silicon chip)
 - Node.js: v18 (LTS)

**Workaround**
Node.js may be configured as ESM then use a JSON file for your mock data (to avoid the `import`/`require` conflict)!

**Comment by ryanblock** [comment]
Good call, we can and should fix this!

**Comment by ryanblock** [comment]
Just released 1.1.0 RC, please give it a try with `npm i @architect/plugin-lambda-invoker@RC --save-dev`.

Please note this caveat as found in the changelog: per [Node.js #2806](https://github.com/nodejs/help/issues/2806), ES module data may be cached in Sandbox, which is intended to be a semi-long-lived process. If using ES modules, you may need to restart Sandbox when updating your mocks.

**Comment by danactive** [comment]
Node.js configured as ESM using _.JS_ or _.MJS_ for my JavaScript mock file uses `export default` hits an exception

Node.js configured as ESM using _.CJS_ for my JavaScript mock file uses `module.exports` hits the same exception



The shared exception on this [line 155](https://github.com/architect/plugin-lambda-invoker/blob/v1.1.0-RC.0/src/index.js#L155).

```
Lambda init error: Cannot use import statement outside a module
```
<img width="820" alt="Screenshot 2023-08-08 at 07 58 35" src="https://github.com/architect/plugin-lambda-invoker/assets/1093286/869ed84c-b794-4b0b-8ec1-dccbafab4737">

**Comment by ryanblock** [comment]
Thanks, I'll take a peek this morning and figure out where the bug is!

**Comment by danactive** [comment]
@ryanblock Correction, I tweaked my side and it works! RC.0 works for both _.JS_ and _.MJS_ with `export default`
and works with _.CJS_ with `module.exports`. It also remains to work with JSON file extension! This issue is closed
